"""update jobs table

Revision ID: 25b9f89e172f
Revises: 1f38b64442dc
Create Date: 2026-07-27 23:53:11.188050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b9f89e172f'
down_revision: Union[str, Sequence[str], None] = '1f38b64442dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('apply_url', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'apply_url')
    # ### end Alembic commands ###
