"""replace cache_hit with response_source

Revision ID: 3cb695db3a48
Revises: fac52a9880bc
Create Date: 2026-07-30 23:15:27.518358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cb695db3a48'
down_revision: Union[str, Sequence[str], None] = 'fac52a9880bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_logs', sa.Column('response_source', sa.String(length=30), nullable=False))
    op.drop_column('search_logs', 'cache_hit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_logs', sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('search_logs', 'response_source')
    # ### end Alembic commands ###
