"""create search_logs table

Revision ID: fac52a9880bc
Revises: 308c548a8be8
Create Date: 2026-07-30 23:10:51.652915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fac52a9880bc'
down_revision: Union[str, Sequence[str], None] = '308c548a8be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_logs',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('client_ip', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_provider'), 'search_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_search_logs_request_hash'), 'search_logs', ['request_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_request_hash'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_provider'), table_name='search_logs')
    op.drop_table('search_logs')
    # ### end Alembic commands ###
